### ISSUE TITLE
Touch Sensor - No Contact

### ISSUE THREAD

**Issue by E3t1jump** [Engineering-3/E3-Touch_Sensor#1]
We have a large number of touch sensors that have a short in them somewhere. I'm not sure at this point if the headers are too small a gauge to make contact with the cable ends or if there may be a broken solder joint or something internal to the button element, or something else.

I will be soldering leads direct to the headers to see if this clears the issue (ergo, header pins not making contact with the cable ends) as a first test step. I will report back after this test.

**Comment by EmbeddedMan** [comment]
Do you mean they have an open? (I.e. broken solder joint would be an open,
not a short.)

**Comment by E3t1jump** [comment]
Correction: Yes, open joint somewhere is the first guess. I'll test per my first post and we can proceed from there to determine if and/or where to find the open.

**Comment by E3t1jump** [comment]
Update:
Observation:
It seemed that wiggling the header intermittently corrected the "open joint behavior." 

Tests Performed:
I soldered leads directly to the header pins: "open joint behavior" unchanged.
I re-soldered the headers to the board: "open joint behavior" unchanged.
Wire harness was triple checked to assure there were no issues with the wires.

Noticed that simply rotating the touch sensor caused the "open joint behavior" to toggle on/off. Then, after a bit the sensor went completely unresponsive (no completed circuit behavior at all).

I will be shipping buggy sensors for review.

**Comment by EmbeddedMan** [comment]
Please and thank you. :-)

**Comment by E3t1jump** [comment]
Found the issue is related to misreading of the silk markings on the back of the sensor coupled with publishing the same misreading in the sensor documentation in the E3 textbook. The sensor works as designed. The documentation will be corrected.
